export const PROJECTS = [
  {
    slug: "mercedes-benz-showroom",
    href: "/projects/mercedes-benz-showroom",
    title: "Mercedes-Benz Showroom",
    category: "Commercial",
    location: "Brisbane, QLD",
    listImg: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Scaffolding for a premium automotive showroom fit-out in Brisbane, requiring precision access solutions across a multi-level structure.",
    heroSubtitle: "Precision scaffolding for a luxury automotive showcase in Brisbane.",
    tags: ["Commercial", "Showroom", "Brisbane"],
    client: { name: "Mercedes-Benz Australia", initials: "MB", color: "#1a1a1a", font: "Orbitron" },
  },
  {
    slug: "nicholson-street-specialist-centre",
    href: "/projects/nicholson-street-specialist-centre",
    title: "Nicholson Street Specialist Centre",
    category: "Commercial",
    location: "Brisbane, QLD",
    listImg: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Complex medical facility requiring strict access control and precision scaffolding engineering throughout the build.",
    heroSubtitle: "Precision scaffolding engineering for a complex medical facility in Brisbane.",
    tags: ["Commercial", "Brisbane", "Completed"],
    client: { name: "Hutchinson Builders", initials: "HB", color: "#E1251B", font: "Barlow Condensed" },
  },
  {
    slug: "okeefe-street-wooloongabba",
    href: "/projects/okeefe-street-wooloongabba",
    title: "O'Keefe Street Wooloongabba",
    category: "Commercial",
    location: "Wooloongabba, QLD",
    listImg: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Large-scale commercial development with coordinated scaffold installation across multiple levels and tight site constraints.",
    heroSubtitle: "Scaffolding built for Brisbane's tightest urban spaces and demanding timelines.",
    tags: ["Commercial", "Urban site", "Completed"],
    client: { name: "Buildcorp", initials: "BC", color: "#E8501A", font: "Bebas Neue" },
  },
  {
    slug: "scaffolding-birdcage",
    href: "/projects/scaffolding-birdcage",
    title: "Scaffolding Birdcage",
    category: "Specialist",
    location: "Southeast Queensland",
    listImg: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Full birdcage scaffold system providing complete overhead access for a major interior project in Southeast Queensland.",
    heroSubtitle: "When you need uninterrupted working deck across an entire ceiling or overhead structure — no gaps, no workarounds — birdcage scaffolding is the engineered solution.",
    tags: ["Specialist", "Birdcage", "Civil"],
    client: { name: "John Holland", initials: "JH", color: "#E10B17", font: "Anton" },
  },
  {
    slug: "willow-apartments",
    href: "/projects/willow-apartments",
    title: "Willow Apartments",
    category: "Residential",
    location: "Queensland",
    listImg: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1439337153520-7082a56a81f4?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Residential multi-level scaffolding requiring precision coordination and staged installation throughout the full construction program.",
    heroSubtitle: "Seven-storey residential development, South East Queensland — full perimeter facade access delivered floor by floor to keep the cladding program on schedule.",
    tags: ["Residential", "Multi-level", "Completed"],
    client: { name: "ADCO Constructions", initials: "AC", color: "#E85A00", font: "Rajdhani" },
  },
  {
    slug: "eagle-street-pier",
    href: "/projects/eagle-street-pier",
    title: "Eagle Street Pier Precinct",
    category: "Commercial",
    location: "Brisbane CBD, QLD",
    listImg: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Multi-level facade and podium scaffolding for a major riverside commercial precinct renovation in Brisbane's CBD.",
    heroSubtitle: "Full perimeter scaffold across an 18-level commercial tower and riverside podium — delivered within a tight CBD programme.",
    tags: ["Commercial", "CBD", "Completed"],
    client: { name: "Buildcorp", initials: "BC", color: "#E8501A", font: "Bebas Neue" },
    stats: [
      { value: "18", label: "Levels of Perimeter Access Scaffold" },
      { value: "12", label: "Weeks On Programme" },
      { value: "3", label: "Staged Dismantle Phases" },
      { value: "Zero", label: "Recordable Safety Incidents" },
    ],
    body: {
      heading: "Riverside CBD — Tight Constraints, No Compromises",
      paragraphs: [
        "The Eagle Street Pier precinct renovation required full perimeter scaffold across an 18-level commercial tower and a riverside podium — all within one of Brisbane's most constrained CBD corridors.",
        "OSG coordinated hoarding, pedestrian gantry, and phased facade access with the principal contractor to maintain building operations and public access throughout the programme.",
        "The riverside elevation presented additional complexity: tidal clearance requirements governed our base-level scaffold design and tie configurations. Every detail was engineered before a single board was set.",
        "Three staged dismantle phases allowed the fit-out programme to begin on the lower floors while upper-level cladding continued — keeping the overall project schedule intact.",
      ],
      img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
      imgAlt: "Eagle Street Pier commercial precinct scaffold",
    },
    testimonial: {
      quote: "They came in, did the work right, and left the site clean. No excuses, no delays. After working with multiple scaffolding contractors in Queensland, OSG stands clearly at the top.",
      name: "Sarah Bennett",
      role: "Site Manager, Eagle Street Pier Precinct",
      company: "Buildcorp",
    },
  },
  {
    slug: "gateway-bridge-maintenance",
    href: "/projects/gateway-bridge-maintenance",
    title: "Gateway Bridge Maintenance",
    category: "Civil",
    location: "Brisbane, QLD",
    listImg: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Specialist civil scaffold for bridge maintenance access across a major Brisbane river crossing.",
    heroSubtitle: "Engineered access scaffold across a live river crossing — safely managed around traffic, tidal conditions, and strict civil safety protocols.",
    tags: ["Civil", "Bridge access", "Completed"],
    client: { name: "Brennan Civil Infrastructure", initials: "BCI", color: "#0065BD", font: "Squada One" },
    stats: [
      { value: "240m", label: "Scaffold Span Across Bridge Structure" },
      { value: "8", label: "Weeks On Programme" },
      { value: "2", label: "Tidal Windows Managed Per Day" },
      { value: "Zero", label: "Recordable Safety Incidents" },
    ],
    body: {
      heading: "Bridge Access — Engineered Around Live Conditions",
      paragraphs: [
        "The Gateway Bridge maintenance contract required access scaffold across 240 metres of live bridge structure above the Brisbane River — a fundamentally different challenge from building-site work.",
        "OSG's civil crew managed two tidal windows per day, coordinating installation and work shifts around river traffic corridors and TMR access restrictions. No scope for improvisation at that height, over that span.",
        "All scaffold was engineered to bridge-specific loadings with independent sign-off before any crew accessed the structure. Civil safety protocols were embedded in every pre-start and every shift handover.",
        "The contract was completed in eight weeks, on programme, with zero recordable incidents — a result that reflects the competency and discipline of a crew that understood the stakes.",
      ],
      img: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",
      imgAlt: "Gateway Bridge maintenance access scaffold",
    },
    testimonial: {
      quote: "We engaged OSG on a bridge maintenance contract — different scale entirely from building sites. Their civil crew arrived organised, knew the site safety requirements cold, and we finished ahead of schedule.",
      name: "Lisa Brennan",
      role: "Contracts Manager, Bridge Maintenance Program",
      company: "Brennan Civil Infrastructure",
    },
  },
  {
    slug: "kangaroo-point-townhouses",
    href: "/projects/kangaroo-point-townhouses",
    title: "Kangaroo Point Townhouses",
    category: "Residential",
    location: "Kangaroo Point, QLD",
    listImg: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Full perimeter residential scaffold across a 12-dwelling townhouse development on a narrow cliff-side site.",
    heroSubtitle: "Perimeter scaffold for a multi-dwelling residential development on one of Brisbane's most constrained riverside sites.",
    tags: ["Residential", "Multi-dwelling", "Completed"],
    client: { name: "Walsh Construction", initials: "WC", color: "#009C7A", font: "Russo One" },
    stats: [
      { value: "12", label: "Dwellings Scaffolded Concurrently" },
      { value: "10", label: "Weeks On Programme" },
      { value: "4", label: "Staged Installation Phases" },
      { value: "Zero", label: "Recordable Safety Incidents" },
    ],
    body: {
      heading: "Cliff-Side Residential — Staged Access Across 12 Dwellings",
      paragraphs: [
        "Kangaroo Point's cliff-side topography makes any construction project demanding. Across 12 dwellings on a narrow, terraced site with limited crane access, OSG delivered full perimeter scaffold across four staged installation phases.",
        "Each phase had to be complete and signed off before the next could begin — site constraints meant sequential working was the only option. OSG's programme management kept each handover on schedule, protecting the downstream trades.",
        "Residential work demands a different kind of discipline from commercial. Neighbours, public footpaths, and tight property boundaries were all factors the crew managed without incident throughout the ten-week programme.",
        "The project was completed on schedule with zero recordable safety incidents — the result Walsh Construction expected and OSG delivered.",
      ],
      img: "https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1200&q=80",
      imgAlt: "Kangaroo Point townhouse perimeter scaffold",
    },
    testimonial: {
      quote: "Safety was never compromised, and the work was finished ahead of schedule. That combination is rare in this industry and OSG delivered it without question.",
      name: "Robert Walsh",
      role: "Director, Walsh Construction",
      company: "Walsh Construction",
    },
  },
  {
    slug: "south-bank-precinct",
    href: "/projects/south-bank-precinct",
    title: "South Bank Precinct Works",
    category: "Civil",
    location: "South Brisbane, QLD",
    listImg: "https://images.unsplash.com/photo-1532619187608-e5375cab36aa?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1532619187608-e5375cab36aa?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Major public precinct scaffold supporting structural maintenance and upgrade works across South Bank's civic infrastructure.",
    heroSubtitle: "Complex access scaffold for civil upgrade works across a major public precinct — with the public present throughout.",
    tags: ["Civil", "Public realm", "Completed"],
    client: { name: "Infrastructure Plus", initials: "IP", color: "#4a3010", font: "Rajdhani" },
    stats: [
      { value: "3,800", label: "m² of Access Scaffold" },
      { value: "20", label: "Weeks On Programme" },
      { value: "5", label: "Active Work Zones Managed" },
      { value: "Zero", label: "Recordable Safety Incidents" },
    ],
    body: {
      heading: "Public Precinct — Access Engineered Around Live Crowds",
      paragraphs: [
        "South Bank is one of Queensland's most heavily trafficked public precincts. Delivering 3,800 m² of civil access scaffold while the precinct remained open to the public required more than good scaffolding — it required genuine site management discipline.",
        "OSG managed five active work zones concurrently across the 20-week programme, each with its own hoarding, exclusion zones, and public-interface protocols. Civilian safety was built into the programme from day one.",
        "The structural maintenance and upgrade scope demanded scaffold that could adapt as the works progressed — sections reconfigured without disrupting adjacent zones or the public realm around them.",
        "Infrastructure Plus nominated OSG specifically for their civil crew's track record on live public sites. We delivered the same discipline they expected: zero incidents, full programme compliance, and a clean site handback.",
      ],
      img: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
      imgAlt: "South Bank precinct civil access scaffold",
    },
    testimonial: {
      quote: "We've worked with many scaffolding companies. O'Neill Scaffolding Group stands apart because they listen and actually deliver what they promise — every single time.",
      name: "David Kumar",
      role: "Senior Engineer, South Bank Precinct Program",
      company: "Infrastructure Plus",
    },
  },
  {
    slug: "fortitude-valley-precinct",
    href: "/projects/fortitude-valley-precinct",
    title: "Fortitude Valley Precinct",
    category: "Civil",
    location: "Fortitude Valley, QLD",
    listImg: "https://images.unsplash.com/photo-1516733968668-dbdce39c4651?auto=format&fit=crop&w=1920&q=80",
    heroImg: "https://images.unsplash.com/photo-1516733968668-dbdce39c4651?auto=format&fit=crop&w=1920&q=80",
    listDesc: "Urban renewal scaffold supporting structural upgrades and facade works across a mixed-use inner-city precinct.",
    heroSubtitle: "Access scaffold for a large-scale urban renewal project in one of Brisbane's busiest inner-city precincts.",
    tags: ["Civil", "Urban renewal", "Completed"],
    client: { name: "Urban Developments", initials: "UD", color: "#CC1417", font: "Chakra Petch" },
    stats: [
      { value: "6", label: "Buildings Scaffolded in Sequence" },
      { value: "14", label: "Weeks On Programme" },
      { value: "Zero", label: "Recordable Safety Incidents" },
      { value: "100%", label: "Programme Milestones Met" },
    ],
    body: {
      heading: "Urban Renewal — Six Buildings, One Coordinated Programme",
      paragraphs: [
        "The Fortitude Valley urban renewal programme covered six buildings across a mixed-use inner-city precinct — each requiring facade and structural access scaffold in a sequenced programme that couldn't afford delays between buildings.",
        "OSG coordinated scaffold installation, active use, and dismantle across all six buildings as a single rolling programme. When one building's work completed, the next was already set up and ready — no gaps in the contractor's programme.",
        "Working in Fortitude Valley means working around live street activity: bars, retail, pedestrian traffic, and narrow lanes. OSG's site management kept the public realm clear and compliant at every stage.",
        "Fourteen weeks, six buildings, 100% of programme milestones met, and zero recordable incidents. That's the standard Urban Developments required — and exactly what OSG delivered.",
      ],
      img: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=80",
      imgAlt: "Fortitude Valley urban renewal scaffold",
    },
    testimonial: {
      quote: "They treated our civil project like it was their own. The attention to detail, the site management, and the safety record all exceeded our expectations.",
      name: "Lisa Chen",
      role: "Project Lead, Fortitude Valley Precinct",
      company: "Urban Developments",
    },
  },
];

export function getProject(slug) {
  return PROJECTS.find((p) => p.slug === slug);
}
